### ISSUE TITLE
 add proposal and add members

### ISSUE THREAD

**Issue by orbeckst** [ASU-CompMethodsPhysics-PHY494/final-2018-phy494_final_baseball#1]
@ASU-CompMethodsPhysics-PHY494/phy494_final_baseball   please

- [x] upload the proposal, which I will review (see issue #2 ) 
- [x] @APeerenb please make sure that all members are in the team

Please close this issue once you have checked both boxes above.

**Comment by tunaLandslide** [comment]
The proposal should be in the submission area of the project repository,
and Tyler has said that he will join the repository

**Comment by orbeckst** [comment]
@tunaLandslide – I am sorry, I think I addressed you in the wrong issue tracker. Please remind me, which one is your team and which one is your repository?

**Comment by tunaLandslide** [comment]
I named it doubularity, it is Tyler Cox and me

**Comment by orbeckst** [comment]
Thanks, just saw it.
